// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBuildsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildInfo {
    #[prost(string, tag = "1")]
    pub build_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub invocation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub identity: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag = "5")]
    pub finished: bool,
    #[prost(string, tag = "6")]
    pub command: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub event_count: i64,
    #[prost(string, tag = "8")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub task_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBuildsResponse {
    #[prost(message, repeated, tag = "1")]
    pub builds: ::prost::alloc::vec::Vec<BuildInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchBuildRequest {
    #[prost(string, tag = "1")]
    pub build_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub invocation_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub start_sequence: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchBuildResponse {
    #[prost(int64, tag = "1")]
    pub sequence_number: i64,
    #[prost(bytes = "bytes", tag = "2")]
    pub bazel_event: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "3")]
    pub event_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// Generated server implementations.
pub mod build_event_subscription_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BuildEventSubscriptionServer.
    #[async_trait]
    pub trait BuildEventSubscription:
        std::marker::Send + std::marker::Sync + 'static
    {
        async fn list_builds(
            &self,
            request: tonic::Request<super::ListBuildsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBuildsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the WatchBuild method.
        type WatchBuildStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::WatchBuildResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn watch_build(
            &self,
            request: tonic::Request<super::WatchBuildRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::WatchBuildStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct BuildEventSubscriptionServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BuildEventSubscriptionServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T: BuildEventSubscription> tonic::server::NamedService
        for BuildEventSubscriptionServer<T>
    {
        const NAME: &'static str = "com.github.trace_machina.nativelink.bep.BuildEventSubscription";
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
        for BuildEventSubscriptionServer<T>
    where
        T: BuildEventSubscription,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/com.github.trace_machina.nativelink.bep.BuildEventSubscription/ListBuilds" => {
                    #[allow(non_camel_case_types)]
                    struct ListBuildsSvc<T: BuildEventSubscription>(pub Arc<T>);
                    impl<T: BuildEventSubscription>
                        tonic::server::UnaryService<super::ListBuildsRequest>
                        for ListBuildsSvc<T>
                    {
                        type Response = super::ListBuildsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListBuildsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BuildEventSubscription>::list_builds(
                                    &inner,
                                    request,
                                )
                                .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListBuildsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/com.github.trace_machina.nativelink.bep.BuildEventSubscription/WatchBuild" => {
                    #[allow(non_camel_case_types)]
                    struct WatchBuildSvc<T: BuildEventSubscription>(pub Arc<T>);
                    impl<T: BuildEventSubscription>
                        tonic::server::ServerStreamingService<super::WatchBuildRequest>
                        for WatchBuildSvc<T>
                    {
                        type Response = super::WatchBuildResponse;
                        type ResponseStream = T::WatchBuildStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WatchBuildRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BuildEventSubscription>::watch_build(
                                    &inner,
                                    request,
                                )
                                .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WatchBuildSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BuildEventSubscriptionServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
}
